[package]
name = "tokio-postgres-rustls"
description = "Rustls integration for tokio-postgres"
version = "0.11.1"
authors = ["Jasper Hugo <jasper@jasperhugo.com>"]
repository = "https://github.com/jbg/tokio-postgres-rustls"
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
ring = { version = "0.17", default-features = false }
rustls = { version = "0.23.1", default-features = false }
tokio = { version = "1", default-features = false }
tokio-postgres = { version = "0.7", default-features = false, features = ["runtime"] }
tokio-rustls = { version = "0.25", default-features = false, features = ["ring"] }
x509-certificate = {version = "0.23", default-features = false }

[dev-dependencies]
env_logger = { version = "0.11", default-features = false }
tokio = { version = "1", features = ["macros", "rt"] }
tokio-postgres = "0.7"
rustls = { version = "0.23" }

[patch.crates-io]
tokio-rustls = { git = "https://github.com/rustls/tokio-rustls", rev = "b3a2b143239d66253ba09f8ac4bfc4b7ab00cfac" }
tokio-postgres = { git = "https://github.com/grafbase/rust-postgres", branch = "grafbase-rebased" }
